name: upro
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.2
  provider: ^6.0.3
  intl: ^0.17.0
  sembast: ^3.3.0
  path_provider: ^2.0.11
  path: ^1.8.2
  image_picker: ^0.8.3+2
  file_picker: ^5.5.0
  open_file: ^3.3.2
  photo_view: ^0.14.0
  google_fonts: ^2.1.0
  smooth_page_indicator: ^1.2.0+3
  http: ^0.13.6
  dio: ^5.5.0+1
  carousel_slider: ^4.2.1
  google_maps_flutter: ^2.9.0
  url_launcher: ^6.3.0
  google_sign_in: ^6.2.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0

  
flutter_icons:
  android: true
  image_path: "images/imron.JPG"

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - images/login/
    - images/client/
    - images/client/Advert/
    - images/admin/
    - images/
  fonts:
    - family: Sarabun
      fonts:
        - asset: fonts/Sarabun-Bold.ttf
          weight: 700